language: node_js
node_js:
  - "10"

sudo: false

env:
  global:
    - secure: "FxioHWbSjf95pYOYOffk2t95Q2eg0lnosz16uqFGuFAsuQ1NRhH7Nr3y9gaPt4ADKO5DUThzEWYICP6PXdJztJsfg2xCvRMEDrVk4T6h+ATFj8jAsO2AWv26s8Rh0t0j0/SwMWe+2PR4BxaZG+2zdYwtr3qf6GkJztyM9lyh7h2EZXs2g8w2gfxlE4qy8gsHqa34/04XJHqqIYqspSPV7wyjr13e0lzqQ7Ll8ikDHR2nkzA3vc+r30vy/gsRhJdzSCjX6Uii0p6TuuRVHjNRp144obmi1J3cf6O3bZdS1hWCoIIp5bY2bHWoeq+FyaVESTKBqZ1AseUaFU4RKXHIYasgNWnwAV7FlpULGCCuzZ7Loy2shyqNxfxcn1WXonHiSomz4Lrgoq4kWy945kkT4njUTDvq4IKV+IH1l1WUC4h4/8QqyoVNpA40wDriEV1gW6N3ccjVhpUfM0SSqPmptno2nArEHdDKoxsv360CB+S6JiWdrDlFOVGXW7G+s2HhwYHfV94uzfhJuDnog2D5wLCbUxVlCn80rgGfzpOL8nyRLNPsB7bXlVpUJGM+YjlaUkP4LLtz1t6/k/eLG46rawER44bL4MXO4ZwHfb88vvlu7yBSCUuzAj1LDpBNP513TiknMmqwYJ3WzCwxWkYfgXZASKA3q8vpuclc1oxsvfA="
    - secure: "C9F67nu3hyqPQLTmLfYl1R/M1Ci1dq0D3bwZqXLDVZACu1tEAg/qtS8Ac96e+UTJfBziEu8HoW0h86qlUt8qTHAh2wA/YZB96Le9dVS4DpH44DQWHi88LlaTaxdByY/zSN4QsrP9bYCWaQmdX1rybpHspsb5yWOwbr6o1ATGfDpnloGcZNDZfCAGD4ukKbZU7b4zSC8Ih8kx4095xmYfP21s0v9jbtfSPCD9MJWbi9RK4BRJLaowbcwMIUj1osuFb5iVcPGGiIpoqaPNHswx9iZxdDSY4lFYzObW6jEl93XRx7NkhgYGAzkwSzOQmS3re57Fq8j1sAm69Mwuy1r+uZKEPAKV3RQlJGOxiZCHwv8u4VmEiBYUEM0zt+QMxQolRHWEvwc+Cn211VgSVnSU/6LNMj8XBCj4BH2WpcQDEulPhJvBfJp1hGGiRl+lNgpJY3etN+bkDzr3o8t05JiTXWlNTtT+apdz3dTJpJWi13nKZgbLLIsyQOTzJTrx7gFELQcCis+dAqEeNCMiHS4gp8HJX9+8Yc3cSaRK7u9ueokWli8aCtdslVAtxJbFOSNrb7zROtMnh6JjqI+bBb27Rjzay6kYHgYWxKWbDMcBO2ejWCD/kfCVV2yHnqJ9rtYBoZQWXmbt8Rb4v9XtUX+0lanbsTT6knqqJZZPNwS5gvE="

cache:
  directories:
    - "node_modules"

addons:
  sauce_connect: true

before_script:
  - npm install

script:
  npx gulp ci

